### PR TITLE
assert to fr (for real)

### PR DESCRIPTION
**Pull request by parkerhendo**
Feature request ([Link](https://x.com/KennethCassel/status/1710049410573345033?s=20))

Adds support for `fr` (for real) in place of `assert`

```javascript
fr(typeof argumentName === "string");
```

### CODE REVIEW

**Comment by LuciooF** [comment]
Once accepted this solves #4 :D slayy king

**Review by christina-de-martinez — COMMENTED** [review]
Would it be easy to fix the whitespace changes? Other than that this looks great, thanks for the contribution!

**Comment by parkerhendo** [comment]
@christina-de-martinez should be fixed now 🫡

**Comment by christina-de-martinez** [comment]
Slay 🙌🏼 sorry one more thing, could you add it to the table in the readme?

**Pull request merged**
