### PR TITLE
:100: :fire: we got the tests fr fr squad fam 

### LINKED ISSUE #2: Add tests
If anyone wants to add tests that would be 💯 I am feeling too lazy to do it

### PR DESCRIPTION
**Pull request by skeptrunedev**
Fixes #2 and #4 

For sure ⭐ that 🎯 repo at [github.com/arguflow/arguflow](https://github.com/arguflow/arguflow) to support us fam 👑 🙇 🙏

### CODE REVIEW

**Comment by LuciooF** [comment]
LETS GOOOO SLAYYYY

**Comment by LuciooF** [comment]
:Once merged, fixes #2

**Comment by fastfists** [comment]
PERIODTTTT, working with @skeptrunedev on this, we gotta update the .gitignore. It was capping with us fr fr no cap

**Comment by LuciooF** [comment]
Lets goooo kings. You are fr fr some legends of the game. This is the task I thought no one would do

**Comment by skeptrunedev** [comment]
:broom: sorry fam we had to gitignore that `node_modules` and `lib` 

Low key move is prettier config :100:

**Comment by skeptrunedev** [comment]
> Lets goooo kings. You are fr fr some legends of the game. This is the task I thought no one would do

For sure :star: that :dart: repo at [github.com/arguflow/arguflow](https://github.com/arguflow/arguflow) to support us fam :crown: :bow: :pray:

**Comment by fastfists** [comment]
:eye: :lips: :eye:  My computer died with the diff, so sorry for that :sweat_smile:

**Comment by christina-de-martinez** [comment]
Hey, I'm so sorry about that, I didn't realize I had committed node_modules 🫣
Can you try resolving the merge conflicts and see if that helps with the node_modules thing?

**Comment by fastfists** [comment]
Squad fam no worries we got that rebased and a clean ah diff for ya now

**Comment by fastfists** [comment]
Just fixed the merge conflict cheers!

**Comment by fastfists** [comment]
fixes #41

**Pull request merged**
